### ISSUE TITLE
Switch to a BED file for primers/amplicons

### ISSUE THREAD

**Issue by fanninpm** [usafsam/mad_river_wf#14]
Currently, we are using two separate files to indicate our primers:

- `reference/primers.fasta`: This is used by BBDuk in the `TRIM_PRIMERS` step. We can generate this using the [`getfasta` command from the bedtools suite](https://bedtools.readthedocs.io/en/latest/content/tools/getfasta.html) and the FASTA provided by Nextclade.
- `reference/midnight_primers_nextclade.tsv`: This is [used by Nextclade](https://docs.nextstrain.org/projects/nextclade/en/stable/user/input-files.html#pcr-primers). I would have to write a script that can combine the BED file, the FASTA and GFF (v2) files provided by Nextclade, and other user-provided information such as "institution" (for some reason).

**Comment by friesac** [comment]
Presumably this is related to our discussion about the performance of specific amplicons and the presumed need to use a bed file to accomplish this based on the location details included in a .bed. For reference, the midnight bed can be found [here](https://zenodo.org/record/3897530#.Yhmn7C-B1QK). That said, i'm just wondering about the rationale you laid out above... 1. BBDuk using the fasta works fine because that ignores position on the genome and just hunts kmers in the reads. 2. This one is more confusing to me... what is the intended output file that you are proposing to combine these for... the output figure?

**Comment by fanninpm** [comment]
> 2. This one is more confusing to me... what is the intended output file that you are proposing to combine these for... the output figure?

This is for Nextclade's output (incorporated into the lineage excel file). Nextclade uses this input to produce the `pcrPrimerChanges` column.

**Comment by friesac** [comment]
So you're talking about the file that comes through on the nextclade container... not something we provide. I don't see why you're proposing to change the format of this file?

**Comment by friesac** [comment]
I don't think I would replace in this case. The file they are providing is comprised of the primers used in diagnostic PCR panels for detecting SARS-CoV-2. Not sequencing as far as I can tell. So, when they align the fastas and observe changes in the priming site for detection primers they output these observations so that folks using those primers in tests would know to update their detection tests. If you had a midnight primer site disrupted then you just wouldn't have any sequence because your primers failed to amplify and subsequently sequence. Midnight primer performance will need to be addressed by using the coordinate information from the bed file in a different way. I'm nearly certain the approach is somewhere in [Artic](https://github.com/artic-network/artic-ncov2019)
